spring:
  application:
    name: consul-server
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        register: true
        serviceName: ${spring.application.name}
        instance-id: ${spring.application.name}-${random.uuid}
        health-check-path: /actuator/health
        health-check-interval: 15s
        prefer-ip-address: true
server:
  port: 8081
