server:
  port: 8080
  servlet:
    context-path: /demo

spring:
  datasource:
    url: jdbc:mysql://192.168.1.2:3306/oneluffy?useSSL=false&serverTimezone=UTC
    username: oneluffy
    password: oneluffy
    driver-class-name: com.mysql.cj.jdbc.Driver

#logging:
#  level:
#    com.oneluffy: debug
#    com.oneluffy.mapper: trace
mybatis:
  configuration:
    # 下划线转驼峰
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mappers/*.xml
