server:
  port: 8003  # 使用不同端口

spring:
  application:
    name: eureka-provider

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}  # 实例ID加上端口号，方便区分
    
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true

info:
  app:
    name: ${spring.application.name}
    description: Eureka Provider Service (Instance 2)
    version: 1.0.0 