server:
  port: 8083

spring:
  config:
    import: 
      - "optional:consul:"
  application:
    name: consul-consumer
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        instance-id: ${spring.application.name}:${server.port}
        prefer-ip-address: true
        ip-address: ${spring.cloud.client.ip-address}
        health-check-path: /actuator/health
        health-check-interval: 10s
      config:
        enabled: true
        format: YAML
        default-context: consulConsumerConfig
        profile-separator: '-'
        data-key: consulConfig
        watch:
          enabled: true
          delay: 1000
        prefixes: config
  profiles:
    active: dev